language: c
sudo: required 
env:
  #- board=arduino:avr:mega:cpu=atmega1280 
  #- board=arduino:avr:megaADK
  - board=arduino:avr:mega:cpu=atmega2560 
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.8.5-linux64.tar.xz 
  - tar xf arduino-1.8.5-linux64.tar.xz
  - sudo mv arduino-1.8.5 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
  - tar -xf arduino-1.8.5-linux64.tar.xz 
  #- cd arduino-1.8.5/
#---Para usar libreria-
  - git clone https://github.com/niclabs/HPack-ino 
  - cd HPack-ino
  - mv HPack ~/build/niclabs/arduino-1.8.5/libraries
  - ln -s $PWD $HOME/arduino_ide/libraries/HPack
  - export PATH="$HOME/arduino_ide:$PATH"
  
  #- mkdir sketchbook
  #- mv test ~/build/niclabs/HPack-ino/sketchbook
  #- mv  -v ~/build/niclabs/HPack-ino/HPack/* ~/build/niclabs/HPack-ino/sketchbook/test
install:
  - arduino --install-library "ArduinoUnit"
script:
  - arduino --verify --board arduino:avr:mega:cpu=atmega2560 /usr/local/share/arduino/examples/01.Basics/Blink/Blink.ino
  #- arduino --verify --board arduino:avr:mega:cpu=atmega2560 ~/build/niclabs/HPack-ino/sketchbook/test/test.ino

notifications:
  email:
    on_success: never
    on_failure: never #always/change/never
