language: c
sudo: required #agilizar build
env:
#placas a utilizar.
  #- board=arduino:avr:mega:cpu=atmega1280 
  #- board=arduino:avr:mega:cpu=atmega2560 
  - board=arduino:avr:megaADK
before_install:
#configuracion previa Arduino
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.6.5-linux64.tar.xz
  - tar xf arduino-1.6.5-linux64.tar.xz
  - sudo mv arduino-1.6.5 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
  - tar -xf arduino-1.6.5-linux64.tar.xz #este comando funciona
  - cd arduino-1.6.5/
  - pwd
  - sudo updatedb
#------------------------------Para usar libreria
 #- /home/travis/build/niclabs/HPack-ino/HPack-ino/sketchbook
  - git clone --depth=50 --branch=master git@github.com:niclabs/HPack-ino.git HPack-ino
  #- SKETCH_LOCATION=/home/travis/build/niclabs/HPack-ino
  - cd ~/build/niclabs/HPack-ino #aqui esta lo de git, arduino folder y deberia estar sketchbook folder
  - mkdir sketchbook
  - cd sketchbook
  - mkdir libraries
  - cd ..
  - ls
  - cd test
  - mv test2.ino ~/build/niclabs/HPack-ino/sketchbook
  - cd ..
  - mv HPack ~/build/niclabs/HPack-ino/arduino-1.6.5/libraries

  #- mv HPack cambiar desde ~/build/niclabs/HPack-ino/HPack-ino/ que es /home/travis/etc a sketchbook/libraries #libraries #mover a librerias de usuario Arduino
  #- mv test ~/build/niclabs/HPack-ino/HPack-ino/ mover de aqui a sketchbook #mover folder de sketch de prueba libreria HPack
#install:
  - arduino --install-library "HPack"

script:
#verificaciones para placas.
 - arduino --verify --board arduino:avr:megaADK /usr/local/share/arduino/examples/01.Basics/Blink/Blink.ino
# - arduino --verify --board arduino:avr:mega:cpu=atmega2560 /usr/local/share/arduino/examples/01.Basics/Blink/Blink.ino
# - arduino --verify --board arduino:avr:mega:cpu=atmega1280 /usr/local/share/arduino/examples/01.Basics/Blink/Blink.ino
# /home/travis/build/niclabs/HPack-ino/HPack-ino/test/test2.ino path donde esta por ahora
#  - arduino --verify --board arduino:avr:megaADK ~sketch/test/test2.ino

notifications:
  email:
    on_success: never
    on_failure: never #always/change/never
