language: c
sudo: required #agilizar build
env:
#placas a utilizar
  #- board=arduino:avr:mega:cpu=atmega1280 
  #- board=arduino:avr:mega:cpu=atmega2560 
  - board=arduino:avr:megaADK
  - sketch="${HOME}/Arduino"
before_install:
#configuracion previa Arduino
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.6.5-linux64.tar.xz
  - tar xf arduino-1.6.5-linux64.tar.xz
  - sudo mv arduino-1.6.5 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
#------------------------------Para usar libreria
  - git clone --depth=50 --branch=master git@github.com:niclabs/HPack-ino.git HPack-ino
 # - git clone https://github.com/niclabs/HPack-ino.git #clonar repo Hpack, privado, ver como hacer.
  - cd HPack-ino
  - locate sketchbook
  #- mv HPack ~sketch/libraries #mover a librerias de usuario Arduino
  #- mv test ~sketch #mover folder de sketch de prueba libreria HPack
#install:
  #- arduino --install-library "HPack"

script:
#verificaciones para placas.
 - arduino --verify --board arduino:avr:megaADK /usr/local/share/arduino/examples/01.Basics/Blink/Blink.ino
# - arduino --verify --board arduino:avr:mega:cpu=atmega2560 /usr/local/share/arduino/examples/01.Basics/Blink/Blink.ino
# - arduino --verify --board arduino:avr:mega:cpu=atmega1280 /usr/local/share/arduino/examples/01.Basics/Blink/Blink.ino
#  - arduino --verify --board arduino:avr:megaADK ~sketch/test/test2.ino

notifications:
  email:
    on_success: always
    on_failure: always #always/change/never
